export const EMPLOYEES_LOADED = 'Employees/EMPLOYEES_LOADED';
export const EMPLOYEE_CREATED = "Employees/EMPLOYEE_CREATED";
export const EMPLOYEE_LOADING = "Employees/EMPLOYEE_LOADING";
export const EMPLOYEE_LOADING_ERROR = "Employees/EMPLOYEE_LOADING_ERROR";
