export const EMPLOYEES_LOADED = 'Employees/EMPLOYEES_LOADED';
export const EMPLOYEE_CREATED = "Employees/EMPLOYEE_CREATED";
export const EMPLOYEES_LOADING = "Employees/EMPLOYEES_LOADING";
export const EMPLOYEES_LOADING_ERROR = "Employees/EMPLOYEES_LOADING_ERROR";
